### PR TITLE
Remove feldspar executable, rename lib to src

### PR DESCRIPTION
**Pull request by emilaxelsson**
Can we remove the feldspar command line program?

It has been commented out since release 0.7. I seem to remember that it didn't really work as expected. When given a file with several Feldspar functions, it would produce C functions for each of them. But usually there is *one* main function, and the others are helper functions that will be inlined into the main function.

### CODE REVIEW

**Comment by emilaxelsson** [comment]
To be clear, it was commented out *before* 0.7.

**Comment by emilaxelsson** [comment]
While we're at it, I think it would be good to separate the C source files from the Haskell ones. I've always been confused to find them in the same directory.

The most backwards-compatible measure would be to keep the C sources in `lib/` (they were thoughtlessly moved to `src/` as part of this PR). We could also put them in `clib/` to make it clear what it is.

I think I'd prefer `clib/`.

**Comment by pjonsson** [comment]
We don't care about the command line program and the fact that it doesn't work seems like a good case for removing it.

I'm not sure if it matters but a technical remark is that you get functions in your C files when you use futures and a few other things.

I think the C files should should remain in `lib/`. That's where a C programmer would expect to find the runtime library.

**Comment by emwap** [comment]
:+1:

Let's remove it. We can resurrect the executable as a separate package if needed.

From a C client perspective I don't think it matters where the C files are in the repository.
For most users, the files will be installed in the expected locations when installing the package.
For us developers, we have some tricks in the `Feldspar.Compiler.Plugins` that will conjure up the right paths. Similar tricks exist in `feldspar-io` and we should probably merge those into this package, but that's for another pull request.

My vote is on `clib/`.

**Comment by josefs** [comment]
If we want to make Feldspar fit nicely into a build system used in production I think it's valuable to have a command line tool. But we can resurrect such a thing later. I agree we should get rid of the current defunct implementation.

**Comment by emilaxelsson** [comment]
OK, good!
I'll go with the 67% majority :-) and use `clib`. I think in the absence of `lib`, this is where you'd look for the runtime library. And the name makes it clear that it doesn't contain Haskell files.

**Comment by emilaxelsson** [comment]
> For us developers, we have some tricks in the `Feldspar.Compiler.Plugins` that will conjure up the right paths. Similar tricks exist in `feldspar-io` and we should probably merge those into this package, but that's for another pull request.

Note that `feldspar-io` uses [`feldsparCIncludes`](../blob/master/src/Feldspar/Compiler.hs) which resides in `feldspar-compiler`.

**Comment by emwap** [comment]
> Note that feldspar-io uses feldsparCIncludes which resides in feldspar-compiler.

Excellent!

**Comment by emwap** [comment]
> If we want to make Feldspar fit nicely into a build system used in production I think it's valuable to have a command line tool.

Agree. I also think it should behave more like a compiler driver in that context.

**Comment by emilaxelsson** [comment]
Could we put the C files directly under `clib`, or is there a point in using `clib/Feldspar/C`?

**Comment by emwap** [comment]
Yes. There is no point in having them in a subdirectory now.

**Comment by pjonsson** [comment]
>>If we want to make Feldspar fit nicely into a build system used in production I think it's valuable to have a command line tool.

>Agree. I also think it should behave more like a compiler driver in that context.

This was the part I was trying to address since Cabal isn't great for interacting with C compilers.

**Comment by emilaxelsson** [comment]
I just noticed that GitHub lost the history of all files when I moved them from `lib` to `src`. I didn't think this would happen. The commit shows where the files came from, but it doesn't seem to be possible to click to get to the previous version... :-(

Do you think this is a problem? If so I should destructively revert the changes as soon as possible. (I have no strong preference either way.)

**Comment by emwap** [comment]
Aha. To keep the history the tree need to be rewritten and force-pushed.
See e.g.
http://thisbythem.com/blog/preserving-history-when-renaming-files-in-git/
and
https://silverdrs.wordpress.com/2014/06/09/why-git-is-sometimes-more-gitty-than-any-other-git-you-are-about-to-ever-encounter/

Maybe we should revert and try this on a branch first.

**Comment by emilaxelsson** [comment]
OK, now I've destructively reverted the pull request. So this means that you should all fetch the current status of the repo before doing any other commits. (Hopefully no-one else has fetched the repo since this morning.)

I'll try out your suggestion on a branch Anders.

A remark: I noticed that the "blame" command actually knew the history of the files. But GitHub's history would only show a single commit for each file.

**Comment by emwap** [comment]
> A remark: I noticed that the "blame" command actually knew the history of the files. But GitHub's history would only show a single commit for each file.

The history is there, but you need to do `git log --follow`, which github doesn't.

**Comment by emilaxelsson** [comment]
Ah, OK.

I gathered from the link you sent that the only way to "keep" history so that GitHub shows it is to *rewrite the whole history* of all files involved. I'm not going to try this :-)

I will just remove the `feldspar` executable and leave the directories unchanged.

It might still be worthwhile to move the C files to `clib/`, but I don't feel like obscuring the history all files just to change the name `lib` to `src`.

**Comment by emwap** [comment]
Yes, let's do in steps. I can try to move things on my side and check if there are any other problems.

**Comment by emwap** [comment]
Ok. Rewriting the history means exactly that. _ALL_ commits will be rewritten to reflect the move.

My vote is on making the move and adding a comment in the commit message that explains why the history is missing and how to retrieve it, see emwap/feldspar-compiler@501e09eb555e8ae0eb9c25f2113159ad2fd2d2d3.

**Comment by emilaxelsson** [comment]
That's fine with me. The message could also mention that "blame" (on GitHub or locally) can be used to some extent to see the history.

One more thing, line 51 in `Feldspar/Compiler.hs` should be updated ("lilb" -> "clib").

**Pull request merged**
